package at.sozvers.noegkk.sckont.kontakt.focus;

import javax.xml.namespace.QName;
import java.net.MalformedURLException;
import java.net.URL;
import jakarta.xml.ws.*;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.6b21 Generated source version: 2.2
 */
@WebServiceClient(name="SCKONTKontaktService_1_0Service", targetNamespace="http://focus.kontakt.sckont.noegkk.sozvers.at/",
				  wsdlLocation="file:/C:/ta30/GIT_IntelliJ/focus360/focus-ws-clients/focus-kontakt-ws-client/src/main/resources/wsdl/SCKONTKontaktService_1_0.wsdl")
public class SCKONTKontaktService10Service extends Service {

  private static final String              BASICURI                            = "http://focus.kontakt.sckont.noegkk.sozvers.at/";
  private static final WebServiceException SCKONTKONTAKTSERVICE10SERVICE_EXCEPTION;
  private static final QName               SCKONTKONTAKTSERVICE10SERVICE_QNAME = new QName(BASICURI, "SCKONTKontaktService_1_0Service");
  private static final URL                 SCKONTKONTAKTSERVICE10SERVICE_WSDL_LOCATION;

  static {
	URL                 url = null;
	WebServiceException e   = null;
	try {
	  url = new URL("file:/C:/ta30/GIT_IntelliJ/focus360/focus-ws-clients/focus-kontakt-ws-client/src/main/resources/wsdl/SCKONTKontaktService_1_0.wsdl");
	} catch(MalformedURLException ex) {
	  e = new WebServiceException(ex);
	}
	SCKONTKONTAKTSERVICE10SERVICE_WSDL_LOCATION = url;
	SCKONTKONTAKTSERVICE10SERVICE_EXCEPTION = e;
  }

  public SCKONTKontaktService10Service() {
	super(__getWsdlLocation(), SCKONTKONTAKTSERVICE10SERVICE_QNAME);
  }

  private static URL __getWsdlLocation() {
	if(SCKONTKONTAKTSERVICE10SERVICE_EXCEPTION != null) {
	  throw SCKONTKONTAKTSERVICE10SERVICE_EXCEPTION;
	}
	return SCKONTKONTAKTSERVICE10SERVICE_WSDL_LOCATION;
  }

  public SCKONTKontaktService10Service(WebServiceFeature... features) {
	super(__getWsdlLocation(), SCKONTKONTAKTSERVICE10SERVICE_QNAME, features);
  }

  public SCKONTKontaktService10Service(URL wsdlLocation) {
	super(wsdlLocation, SCKONTKONTAKTSERVICE10SERVICE_QNAME);
  }

  public SCKONTKontaktService10Service(URL wsdlLocation, WebServiceFeature... features) {
	super(wsdlLocation, SCKONTKONTAKTSERVICE10SERVICE_QNAME, features);
  }

  public SCKONTKontaktService10Service(URL wsdlLocation, QName serviceName) {
	super(wsdlLocation, serviceName);
  }

  public SCKONTKontaktService10Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
	super(wsdlLocation, serviceName, features);
  }

  /**
   * @return returns SCKONTKontaktService10
   */
  @WebEndpoint(name="SCKONTKontaktService_1_0Port")
  public SCKONTKontaktService10 getSCKONTKontaktService10Port() {
	return super.getPort(new QName(BASICURI, "SCKONTKontaktService_1_0Port"), SCKONTKontaktService10.class);
  }

  /**
   * @param features
   * 		A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
   *
   * @return returns SCKONTKontaktService10
   */
  @WebEndpoint(name="SCKONTKontaktService_1_0Port")
  public SCKONTKontaktService10 getSCKONTKontaktService10Port(WebServiceFeature... features) {
	return super.getPort(new QName(BASICURI, "SCKONTKontaktService_1_0Port"), SCKONTKontaktService10.class, features);
  }
}
