package at.sozvers.noegkk.sckont.kontakt.focus;

import jakarta.jws.*;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.6b21 Generated source version: 2.2
 */
@WebService(name="SCKONTKontaktService_1_0", targetNamespace="http://focus.kontakt.sckont.noegkk.sozvers.at/")
@SOAPBinding(parameterStyle=SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({ObjectFactory.class})
public interface SCKONTKontaktService10 {

  /**
   * @param kontaktAufggAaMstMapErmitteln
   *
   * @return returns at.sozvers.noegkk.sckont.kontakt.focus.KontaktAufggAaMstMapErmittelnResponse
   */
  @WebMethod
  @WebResult(name="kontaktAufggAaMstMapErmittelnResponse", targetNamespace="http://focus.kontakt.sckont.noegkk.sozvers.at/", partName="kontaktAufggAaMstMapErmittelnResponse")
  public KontaktAufggAaMstMapErmittelnResponse kontaktAufggAaMstMapErmitteln(@WebParam(name="kontaktAufggAaMstMapErmitteln", targetNamespace="http://focus.kontakt.sckont.noegkk.sozvers.at/",
																					   partName="kontaktAufggAaMstMapErmitteln") KontaktAufggAaMstMapErmittelnRequest kontaktAufggAaMstMapErmitteln);

  /**
   * @param kontaktAufggKtMstMapErmitteln
   *
   * @return returns at.sozvers.noegkk.sckont.kontakt.focus.KontaktAufggKtMstMapErmittelnResponse
   */
  @WebMethod
  @WebResult(name="kontaktAufggKtMstMapErmittelnResponse", targetNamespace="http://focus.kontakt.sckont.noegkk.sozvers.at/", partName="kontaktAufggKtMstMapErmittelnResponse")
  public KontaktAufggKtMstMapErmittelnResponse kontaktAufggKtMstMapErmitteln(@WebParam(name="kontaktAufggKtMstMapErmitteln", targetNamespace="http://focus.kontakt.sckont.noegkk.sozvers.at/",
																					   partName="kontaktAufggKtMstMapErmitteln") KontaktAufggKtMstMapErmittelnRequest kontaktAufggKtMstMapErmitteln);

  /**
   * @param kontaktAufggSubMapErmitteln
   *
   * @return returns at.sozvers.noegkk.sckont.kontakt.focus.KontaktAufggSubMapErmittelnResponse
   */
  @WebMethod
  @WebResult(name="kontaktAufggSubMapErmittelnResponse", targetNamespace="http://focus.kontakt.sckont.noegkk.sozvers.at/", partName="kontaktAufggSubMapErmittelnResponse")
  public KontaktAufggSubMapErmittelnReponse kontaktAufggSubMapErmitteln(@WebParam(name="kontaktAufggSubMapErmitteln", targetNamespace="http://focus.kontakt.sckont.noegkk.sozvers.at/",
																				  partName="kontaktAufggSubMapErmitteln") KontaktAufggSubMapErmittelnRequest kontaktAufggSubMapErmitteln);

  /**
   * @param kontaktAufggThemaMstMapErmitteln
   *
   * @return returns at.sozvers.noegkk.sckont.kontakt.focus.KontaktAufggThemaMstMapErmittelnResponse
   */
  @WebMethod
  @WebResult(name="kontaktAufggThemaMstMapErmittelnResponse", targetNamespace="http://focus.kontakt.sckont.noegkk.sozvers.at/", partName="kontaktAufggThemaMstMapErmittelnResponse")
  public KontaktAufggThemaMstMapErmittelnResponse kontaktAufggThemaMstMapErmitteln(@WebParam(name="kontaktAufggThemaMstMapErmitteln", targetNamespace="http://focus.kontakt.sckont.noegkk.sozvers.at/",
																							 partName="kontaktAufggThemaMstMapErmitteln") KontaktAufggThemaMstMapErmittelnRequest kontaktAufggThemaMstMapErmitteln);

  /**
   * @param kontaktHistorieErmitteln
   *
   * @return returns at.sozvers.noegkk.sckont.kontakt.focus.KontaktHistorieErmittelnResponse
   */
  @WebMethod
  @WebResult(name="kontaktHistorieErmittelnResponse", targetNamespace="http://focus.kontakt.sckont.noegkk.sozvers.at/", partName="kontaktHistorieErmittelnResponse")
  public KontaktHistorieErmittelnResponse kontaktHistorieErmitteln(@WebParam(name="kontaktHistorieErmitteln", targetNamespace="http://focus.kontakt.sckont.noegkk.sozvers.at/",
																			 partName="kontaktHistorieErmitteln") KontaktHistorieErmittelnRequest kontaktHistorieErmitteln);

  /**
   * @param kontaktUnterthemenErmitteln
   *
   * @return returns at.sozvers.noegkk.sckont.kontakt.focus.KontaktUnterthemenErmittelnResponse
   */
  @WebMethod
  @WebResult(name="kontaktUnterthemaErmittelnResponse", targetNamespace="http://focus.kontakt.sckont.noegkk.sozvers.at/", partName="kontaktUnterthemenErmittelnResponse")
  public KontaktUnterthemenErmittelnResponse kontaktUnterthemenErmitteln(@WebParam(name="kontaktUnterthemenErmitteln", targetNamespace="http://focus.kontakt.sckont.noegkk.sozvers.at/",
																				   partName="kontaktUnterthemenErmitteln") KontaktUnterthemenErmittelnRequest kontaktUnterthemenErmitteln);

  /**
   * @param kontaktabschlussartErmitteln
   *
   * @return returns at.sozvers.noegkk.sckont.kontakt.focus.KontaktabschlussartErmittelnResponse
   */
  @WebMethod
  @WebResult(name="kontaktabschlussartErmittelnResponse", targetNamespace="http://focus.kontakt.sckont.noegkk.sozvers.at/", partName="kontaktabschlussartErmittelnResponse")
  public KontaktabschlussartErmittelnResponse kontaktabschlussartErmitteln(@WebParam(name="kontaktabschlussartErmitteln", targetNamespace="http://focus.kontakt.sckont.noegkk.sozvers.at/",
																					 partName="kontaktabschlussartErmitteln") KontaktabschlussartErmittelnRequest kontaktabschlussartErmitteln);

  /**
   * @param kontaktaufgabengebietErmitteln
   *
   * @return returns at.sozvers.noegkk.sckont.kontakt.focus.KontaktaufgabengebietErmittelnResponse
   */
  @WebMethod
  @WebResult(name="kontaktaufgabengebietErmittelnResponse", targetNamespace="http://focus.kontakt.sckont.noegkk.sozvers.at/", partName="kontaktaufgabengebietErmittelnResponse")
  public KontaktaufgabengebietErmittelnResponse kontaktaufgabengebietErmitteln(@WebParam(name="kontaktaufgabengebietErmitteln", targetNamespace="http://focus.kontakt.sckont.noegkk.sozvers.at/",
																						 partName="kontaktaufgabengebietErmitteln") KontaktaufgabengebietErmittelnRequest kontaktaufgabengebietErmitteln);

  /**
   * @param kontaktkontaktAendern
   *
   * @return returns at.sozvers.noegkk.sckont.kontakt.focus.KontaktkontaktAendernResponse
   */
  @WebMethod
  @WebResult(name="kontaktkontaktAendernResponse", targetNamespace="http://focus.kontakt.sckont.noegkk.sozvers.at/", partName="kontaktkontaktAendernResponse")
  public KontaktkontaktAendernResponse kontaktkontaktAendern(@WebParam(name="kontaktkontaktAendern", targetNamespace="http://focus.kontakt.sckont.noegkk.sozvers.at/",
																	   partName="kontaktkontaktAendern") KontaktkontaktAendernRequest kontaktkontaktAendern);

  /**
   * @param kontaktkontaktErstellen
   *
   * @return returns at.sozvers.noegkk.sckont.kontakt.focus.KontaktkontaktErstellenResponse
   */
  @WebMethod
  @WebResult(name="kontaktkontaktErstellenResponse", targetNamespace="http://focus.kontakt.sckont.noegkk.sozvers.at/", partName="kontaktkontaktErstellenResponse")
  public KontaktkontaktErstellenResponse kontaktkontaktErstellen(@WebParam(name="kontaktkontaktErstellen", targetNamespace="http://focus.kontakt.sckont.noegkk.sozvers.at/",
																		   partName="kontaktkontaktErstellen") KontaktkontaktErstellenRequest kontaktkontaktErstellen);

  /**
   * @param kontaktkontaktLesen
   *
   * @return returns at.sozvers.noegkk.sckont.kontakt.focus.KontaktkontaktLesenResponse
   */
  @WebMethod
  @WebResult(name="kontaktkontaktLesenResponse", targetNamespace="http://focus.kontakt.sckont.noegkk.sozvers.at/", partName="kontaktkontaktLesenResponse")
  public KontaktkontaktLesenResponse kontaktkontaktLesen(
		  @WebParam(name="kontaktkontaktLesen", targetNamespace="http://focus.kontakt.sckont.noegkk.sozvers.at/", partName="kontaktkontaktLesen") KontaktkontaktLesenRequest kontaktkontaktLesen);

  /**
   * @param kontaktkontaktLoeschen
   *
   * @return returns at.sozvers.noegkk.sckont.kontakt.focus.KontaktkontaktLoeschenResponse
   */
  @WebMethod
  @WebResult(name="kontaktkontaktLoeschenResponse", targetNamespace="http://focus.kontakt.sckont.noegkk.sozvers.at/", partName="kontaktkontaktLoeschenResponse")
  public KontaktkontaktLoeschenResponse kontaktkontaktLoeschen(@WebParam(name="kontaktkontaktLoeschen", targetNamespace="http://focus.kontakt.sckont.noegkk.sozvers.at/",
																		 partName="kontaktkontaktLoeschen") KontaktkontaktLoeschenRequest kontaktkontaktLoeschen);

  /**
   * @param kontaktkontaktartErmitteln
   *
   * @return returns at.sozvers.noegkk.sckont.kontakt.focus.KontaktkontaktartErmittelnResponse
   */
  @WebMethod
  @WebResult(name="kontaktkontaktartErmittelnResponse", targetNamespace="http://focus.kontakt.sckont.noegkk.sozvers.at/", partName="kontaktkontaktartErmittelnResponse")
  public KontaktkontaktartErmittelnResponse kontaktkontaktartErmitteln(@WebParam(name="kontaktkontaktartErmitteln", targetNamespace="http://focus.kontakt.sckont.noegkk.sozvers.at/",
																				 partName="kontaktkontaktartErmitteln") KontaktkontaktartErmittelnRequest kontaktkontaktartErmitteln);

  /**
   * @param kontaktkontakteErmitteln
   *
   * @return returns at.sozvers.noegkk.sckont.kontakt.focus.KontaktkontaktErmittelnResponse
   */
  @WebMethod
  @WebResult(name="kontaktkontakteErmittelnResponse", targetNamespace="http://focus.kontakt.sckont.noegkk.sozvers.at/", partName="kontaktkontakteErmittelnResponse")
  public KontaktkontaktErmittelnResponse kontaktkontakteErmitteln(@WebParam(name="kontaktkontakteErmitteln", targetNamespace="http://focus.kontakt.sckont.noegkk.sozvers.at/",
																			partName="kontaktkontakteErmitteln") KontaktkontaktErmittelnRequest kontaktkontakteErmitteln);

  /**
   * @param kontaktthemaErmitteln
   *
   * @return returns at.sozvers.noegkk.sckont.kontakt.focus.KontaktthemaErmittelnResponse
   */
  @WebMethod
  @WebResult(name="kontaktthemaErmittelnResponse", targetNamespace="http://focus.kontakt.sckont.noegkk.sozvers.at/", partName="kontaktthemaErmittelnResponse")
  public KontaktthemaErmittelnResponse kontaktthemaErmitteln(@WebParam(name="kontaktthemaErmitteln", targetNamespace="http://focus.kontakt.sckont.noegkk.sozvers.at/",
																	   partName="kontaktthemaErmitteln") KontaktthemaErmittelnRequest kontaktthemaErmitteln);

  /**
   * @param leseGueltigeOes
   *
   * @return returns at.sozvers.noegkk.sckont.kontakt.focus.GueltigeOeErmittelnResponse
   */
  @WebMethod
  @WebResult(name="leseGueltigeOesResponse", targetNamespace="http://focus.kontakt.sckont.noegkk.sozvers.at/", partName="leseGueltigeOesResponse")
  public GueltigeOesErmittelnResponse leseGueltigeOes(
		  @WebParam(name="leseGueltigeOes", targetNamespace="http://focus.kontakt.sckont.noegkk.sozvers.at/", partName="leseGueltigeOes") GueltigeOesErmittelnRequest leseGueltigeOes);

  /**
   * @param offeneKontakteErmitteln
   *
   * @return returns at.sozvers.noegkk.sckont.kontakt.focus.OffeneKontakteErmittelnResponse
   */
  @WebMethod
  @WebResult(name="offeneKontakteErmittelnResponse", targetNamespace="http://focus.kontakt.sckont.noegkk.sozvers.at/", partName="offeneKontakteErmittelnResponse")
  public OffeneKontakteErmittelnResponse offeneKontakteErmitteln(@WebParam(name="offeneKontakteErmitteln", targetNamespace="http://focus.kontakt.sckont.noegkk.sozvers.at/",
																		   partName="offeneKontakteErmitteln") OffeneKontakteErmittelnRequest offeneKontakteErmitteln);

  /**
   * @param offeneKontakteErmittelnForFS
   *
   * @return returns at.sozvers.noegkk.sckont.kontakt.focus.OffeneKontakteErmittelnForFSResponse
   */
  @WebMethod
  @WebResult(name="offeneKontakteErmittelnForFSResponse", targetNamespace="http://focus.kontakt.sckont.noegkk.sozvers.at/", partName="offeneKontakteErmittelnForFSResponse")
  public OffeneKontakteErmittelnForFSResponse offeneKontakteErmittelnForFS(@WebParam(name="offeneKontakteErmittelnForFS", targetNamespace="http://focus.kontakt.sckont.noegkk.sozvers.at/",
																					 partName="offeneKontakteErmittelnForFS") OffeneKontakteErmittelnForFSRequest offeneKontakteErmittelnForFS);
}
