package at.sozvers.kva.definitions.angehoerigenbeziehung.suchen;

import at.sozvers.kva.schema.angehoerigenbeziehung.suchen.AngehoerigenBeziehungErmittelnRequest;
import at.sozvers.kva.schema.angehoerigenbeziehung.suchen.AngehoerigenBeziehungErmittelnResponse;
import jakarta.jws.*;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.3.2 Generated source version: 2.2
 */
@WebService(name="AngehoerigenbeziehungenSuchen", targetNamespace="http://kva.sozvers.at/definitions/angehoerigenbeziehung/suchen")
@XmlSeeAlso({at.sozvers.kva.schema.angehoerigenbeziehung.suchen.ObjectFactory.class, at.sozvers.kva.schema.types.ObjectFactory.class})
public interface AngehoerigenbeziehungenSuchen {

  /**
   * @param angehoerigenBeziehungErmittelnRequest
   *
   * @return returns at.sozvers.kva.schema.angehoerigenbeziehung.suchen.AngehoerigenBeziehungErmittelnResponse
   */
  @WebMethod
  @WebResult(name="angehoerigenBeziehungErmittelnResponse", targetNamespace="http://kva.sozvers.at/schema/angehoerigenbeziehung/suchen")
  @RequestWrapper(localName="sucheAngehoerige", targetNamespace="http://kva.sozvers.at/schema/angehoerigenbeziehung/suchen",
				  className="at.sozvers.kva.schema.angehoerigenbeziehung.suchen.AngehoerigenBeziehungErmittelnRequestWrapper")
  @ResponseWrapper(localName="sucheAngehoerigeResponse", targetNamespace="http://kva.sozvers.at/schema/angehoerigenbeziehung/suchen",
				   className="at.sozvers.kva.schema.angehoerigenbeziehung.suchen.AngehoerigenBeziehungErmittelnResponseWrapper")
  public AngehoerigenBeziehungErmittelnResponse sucheAngehoerige(@WebParam(name="angehoerigenBeziehungErmittelnRequest",
																		   targetNamespace="http://kva.sozvers.at/schema/angehoerigenbeziehung/suchen") AngehoerigenBeziehungErmittelnRequest angehoerigenBeziehungErmittelnRequest);

  /**
   * @param angehoerigenBeziehungErmittelnRequest
   *
   * @return returns at.sozvers.kva.schema.angehoerigenbeziehung.suchen.AngehoerigenBeziehungErmittelnResponse
   */
  @WebMethod
  @WebResult(name="angehoerigenBeziehungErmittelnResponse", targetNamespace="http://kva.sozvers.at/schema/angehoerigenbeziehung/suchen")
  @RequestWrapper(localName="sucheVersicherte", targetNamespace="http://kva.sozvers.at/schema/angehoerigenbeziehung/suchen",
				  className="at.sozvers.kva.schema.angehoerigenbeziehung.suchen.AngehoerigenBeziehungErmittelnRequestWrapper")
  @ResponseWrapper(localName="sucheVersicherteResponse", targetNamespace="http://kva.sozvers.at/schema/angehoerigenbeziehung/suchen",
				   className="at.sozvers.kva.schema.angehoerigenbeziehung.suchen.AngehoerigenBeziehungErmittelnResponseWrapper")
  public AngehoerigenBeziehungErmittelnResponse sucheVersicherte(@WebParam(name="angehoerigenBeziehungErmittelnRequest",
																		   targetNamespace="http://kva.sozvers.at/schema/angehoerigenbeziehung/suchen") AngehoerigenBeziehungErmittelnRequest angehoerigenBeziehungErmittelnRequest);
}
