= FOCUS360: Installationshandbuch
:author: Ing. Sascha Ernst Pucher
:email: sascha.pucher@oegk.at
:cc-email: focus360@oegk.at
:toc:
:toc-title: Inhaltsverzeichnis
:sectnums:
:chapter-signifier: {empty}
:table-caption: Tabelle

== Dokumentenverwaltung

.Versionsgeschichte
[cols="4*<.^"]
|===
|{empty} ^.^|Versionsnummer ^.^|Erstellung ^.^|Ersteller

|Initiale Erstellung|4.9.8|19.11.2024|Rene Brunner
|Überarbeitete Version ab RS KIEL |{revnumber}|{revdate}|{author}
|===

== Allgemein

=== Releasekennzeichnung

.Releasekennzeichnung
[cols="3*<.^"]
|===
^.^|Produktname ^.^|Versionsnummer ^.^|Releaseart

|SCKONT|{revnumber}|{release-type}
|===

=== Gültig bis

Diese Installationsanleitung gilt vom Datum der Erstellung bis zu einer inkompatiblen Änderung in einer der vorausgesetzten Komponenten.

=== Ansprechpartner

* Team der Unternehmenssoftware & -services der Landesstelle Steiermark - {cc-email}
* Erwin Kaplan - erwin.kaplan@oegk.at

== Applikation Erstinstallation

=== Systemvoraussetzung

Voraussetzung für die Installation ist eine RS2023 (KIEL) konforme Umgebung und die Implementierung der durch das ePortal-Team beschriebenen Deployment-Automatisierung mittels Control-Tier.

== Applikation Installation / Upgrade

=== Systemvoraussetzung

Voraussetzung für die Installation ist eine RS2023 (KIEL) konforme Umgebung und die Implementierung der durch das ePortal-Team beschriebenen Deployment-Automatisierung mittels Control-Tier.
Die Komponenten sind über RDM ausgeliefert und in Unterordner aufgeteilt.

=== Installationsbeschreibung

Die Installation erfolgt durch das Durchführen des automatisierten Deployments auf den Ziel-Servern.
Diese sind anhand des Properties _targettype_ in der Datei _deploy-info_ angegeben.
Die Installationsreihenfolge ist anhand des _sequence_-Propertys angegeben.

=== Konfiguration

Die Konfiguration erfolgt ausschließlich über Parameter im Control-Tier.

==== Konfiguration "FOCUS360 Frontend"

Folgende Parameter müssen gesetzt werden und sind unter folgendem Link auf confluence zu finden:
https://doku.seu.sozvers.at/confluence_secure/display/QDASH/Umgebungsparameter[Confluence Umgebungsparameter]

== Datenbank

=== Erstinstallation

==== Installationsabfolge (Installation erfolgt mittels SFC)

conf.sh

==== Konfiguration

Folgende Parameter müssen gesetzt werden und sind unter folgendem Link auf confluence zu finden:
https://doku.seu.sozvers.at/confluence_secure/display/QDASH/Umgebungsparameter[Confluence Umgebungsparameter]

=== Upgrade

Ein Datenbank-Upgrade wird nicht benötigt.

== Sonstiges

=== Parameter

Folgende Parameter müssen gesetzt werden und sind unter folgendem Link auf confluence zu finden:
https://doku.seu.sozvers.at/confluence_secure/display/QDASH/Umgebungsparameter[Confluence Umgebungsparameter]

=== Behandlung weiterer Liefergegenstände

Keine

=== Abschlussarbeiten Upgrade

Keine

=== Tools und Werkzeuge

Die Struktur und das Tooling des Konzepts zur Deployment-Automatisierung sind in <<ePortal-Deploy-Auto>> beschrieben.

Details zum Produkt und zur Anwendungsentwicklung sind in <<FOCUS360-Confluence-Seite>> beschrieben.

[bibliography]
== Verweise

* [[[ePortal-Deploy-Auto]]] Klaus Dorninger, ITSV GmbH - ePortal Deployment Automatisierung.
URL: http://buildrep.seu.sozvers.at/service/local/repositories/releases/content/at/itsv/eportal/eportal-jboss7-deployment-automation-doc-pdf/1.0.0/eportal-jboss7-deployment-automation-doc-pdf-1.0.0-doc.pdf[eportal-jboss7-deployment-automation-doc-pdf-1.0 .0-doc.pdf]
* [[[FOCUS360-Confluence-Seite]]] Erwin Kaplan und Sascha Pucher, ÖGK - IT Management und IT Organisation - TF Softwareentwicklung - Unternehmenssoftware & -service - Focus360 Confluence Space URL: https://doku.seu.sozvers.at/confluence_secure/display/QDASH/FOCUS360+-+Startseite[FOCUS360 - Startseite]

[glossary]
== Glossar

[glossary]
Technisches Portal:: Unter einem technischen Portal wird die tatsächliche Anwendung der Java-Portaltechnologie unter Verwendung eines
Portalservers und entsprechenden Portlets verstanden.
Ein Vertreter eines Portalservers ist das Open Source Produkt "JBoss Portal".
Organisatorisches Portal:: Unter einem organisatorischen Portal wird ein Internetportal verstanden, das dem Benutzer als eine Einheit bzw.
Anwendung bereitgestellt wird, ohne dass dies aus technischer Sicht tatsächlich so ist.
So können verschiedene Anwendungen auch auf verschiedenen Webservern installiert sein, ohne dass dies für den Benutzer von Bedeutung ist.
Verantwortlich dafür sind in erster Linie Funktionen wie Single Sign On (SSO) und ein einheitliches Layout.
Single Sign On:: "Single Sign On" bezeichnet das einmalige Anmelden (Authentifizieren) an einem Portal.
In weiterer Folge kann der identifizierte User mit allen Anwendungen, für die er autorisiert ist, innerhalb dieses Portals arbeiten, ohne sich für jede einzelne neu anmelden zu müssen.
PVP:: Portalverbund Portal des Bundesrechenzentrums

