package at.sozvers.kva.definitions.gebuehrenbefreiung.suchen;

import at.sozvers.kva.schema.gebuehrenbefreiung.suchen.GebuehrenbefreiunRequest;
import at.sozvers.kva.schema.gebuehrenbefreiung.suchen.GebuehrenbefreiunResponse;
import jakarta.jws.*;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.3.2 Generated source version: 2.2
 */
@WebService(name="GebuehrenbefreiungSuchen", targetNamespace="http://kva.sozvers.at/definitions/gebuehrenbefreiung/suchen")
@XmlSeeAlso({at.sozvers.kva.schema.gebuehrenbefreiung.suchen.ObjectFactory.class, at.sozvers.kva.schema.types.ObjectFactory.class})
public interface GebuehrenbefreiungSuchen {

  /**
   * @param gebuehrenbefreiunRequest
   *
   * @return returns at.sozvers.kva.schema.gebuehrenbefreiung.suchen.GebuehrenbefreiunResponse
   */
  @WebMethod
  @WebResult(name="gebuehrenbefreiunResponse", targetNamespace="http://kva.sozvers.at/schema/gebuehrenbefreiung/suchen")
  @RequestWrapper(localName="suchen", targetNamespace="http://kva.sozvers.at/schema/gebuehrenbefreiung/suchen",
				  className="at.sozvers.kva.schema.gebuehrenbefreiung.suchen.GebuehrenbefreiunRequestWrapper")
  @ResponseWrapper(localName="suchenResponse", targetNamespace="http://kva.sozvers.at/schema/gebuehrenbefreiung/suchen",
				   className="at.sozvers.kva.schema.gebuehrenbefreiung.suchen.GebuehrenbefreiunnResponseWrapper")
  public GebuehrenbefreiunResponse suchen(
		  @WebParam(name="gebuehrenbefreiunRequest", targetNamespace="http://kva.sozvers.at/schema/gebuehrenbefreiung/suchen") GebuehrenbefreiunRequest gebuehrenbefreiunRequest);
}
