-- psql -f .\init_db_local.sql -U postgres

DROP DATABASE IF EXISTS focus;
DROP USER IF EXISTS focus;

CREATE USER focus WITH
    LOGIN
    NOSUPERUSER
    NOINHERIT
    NOCREATEDB
    NOCREATEROLE
    NOBYPASSRLS
    NOREPLICATION
    CONNECTION LIMIT -1
    ENCRYPTED PASSWORD 'focus';
CREATE DATABASE focus WITH
    OWNER = focus
    ENCODING = 'UTF8'
    CONNECTION LIMIT = -1;