package at.itsv.services.lgkk;

import javax.xml.namespace.QName;
import java.net.MalformedURLException;
import java.net.URL;
import jakarta.xml.ws.*;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.6b21 Generated source version: 2.2
 */
@WebServiceClient(name="Focus360WsImplService", targetNamespace="http://v20.focus360.webservice.lgkk.stp.sozvers.at/",
				  wsdlLocation="file:/C:/ta3j/workspaces/QDASH/focus-ws-clients/focus-lgkk-ws-client/src/main/resources/wsdl/Focus360WsV20.wsdl")
public class Focus360WsImplService extends Service {

  private final static WebServiceException FOCUS360WSIMPLSERVICE_EXCEPTION;
  private final static QName               FOCUS360WSIMPLSERVICE_QNAME = new QName("http://v20.focus360.webservice.lgkk.stp.sozvers.at/", "Focus360WsImplService");
  private final static URL                 FOCUS360WSIMPLSERVICE_WSDL_LOCATION;

  static {
	URL                 url = null;
	WebServiceException e   = null;
	try {
	  url = new URL("file:/C:/ta3j/workspaces/QDASH/focus-ws-clients/focus-lgkk-ws-client/src/main/resources/wsdl/Focus360WsV20.wsdl");
	} catch(MalformedURLException ex) {
	  e = new WebServiceException(ex);
	}
	FOCUS360WSIMPLSERVICE_WSDL_LOCATION = url;
	FOCUS360WSIMPLSERVICE_EXCEPTION = e;
  }

  public Focus360WsImplService() {
	super(__getWsdlLocation(), FOCUS360WSIMPLSERVICE_QNAME);
  }

  private static URL __getWsdlLocation() {
	if(FOCUS360WSIMPLSERVICE_EXCEPTION != null) {
	  throw FOCUS360WSIMPLSERVICE_EXCEPTION;
	}
	return FOCUS360WSIMPLSERVICE_WSDL_LOCATION;
  }

  public Focus360WsImplService(WebServiceFeature... features) {
	super(__getWsdlLocation(), FOCUS360WSIMPLSERVICE_QNAME, features);
  }

  public Focus360WsImplService(URL wsdlLocation) {
	super(wsdlLocation, FOCUS360WSIMPLSERVICE_QNAME);
  }

  public Focus360WsImplService(URL wsdlLocation, WebServiceFeature... features) {
	super(wsdlLocation, FOCUS360WSIMPLSERVICE_QNAME, features);
  }

  public Focus360WsImplService(URL wsdlLocation, QName serviceName) {
	super(wsdlLocation, serviceName);
  }

  public Focus360WsImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
	super(wsdlLocation, serviceName, features);
  }

  /**
   * @return returns Focus360WsV20
   */
  @WebEndpoint(name="Focus360WsV20Port")
  public Focus360WsV20 getFocus360WsV20Port() {
	return super.getPort(new QName("http://v20.focus360.webservice.lgkk.stp.sozvers.at/", "Focus360WsV20Port"), Focus360WsV20.class);
  }

  /**
   * @param features
   * 		A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
   *
   * @return returns Focus360WsV20
   */
  @WebEndpoint(name="Focus360WsV20Port")
  public Focus360WsV20 getFocus360WsV20Port(WebServiceFeature... features) {
	return super.getPort(new QName("http://v20.focus360.webservice.lgkk.stp.sozvers.at/", "Focus360WsV20Port"), Focus360WsV20.class, features);
  }
}
