package at.itsv.services.lgkk;

import java.util.concurrent.Future;
import at.sozvers.stp.lgkk.webservice.focus360.v20.*;
import jakarta.jws.*;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.AsyncHandler;
import jakarta.xml.ws.Response;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.6b21 Generated source version: 2.2
 */
@WebService(name="Focus360WsV20", targetNamespace="http://v20.focus360.webservice.lgkk.stp.sozvers.at/")
@SOAPBinding(parameterStyle=SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({at.itsv.services.lgkk.ObjectFactory.class, at.sozvers.stp.lgkk.webservice.focus360.v20.ObjectFactory.class})
public interface Focus360WsV20 {

  /**
   * @param parameters
   *
   * @return returns at.sozvers.stp.lgkk.webservice.focus360.v20.SucheLGKDokumenteV1Response
   */
  @WebMethod
  @WebResult(name="sucheLGKDokumenteV1Response", targetNamespace="http://v20.focus360.webservice.lgkk.stp.sozvers.at/", partName="parameters")
  public SucheLGKDokumenteV1Response sucheLGKDokumenteV1(
		  @WebParam(name="sucheLGKDokumenteV1", targetNamespace="http://v20.focus360.webservice.lgkk.stp.sozvers.at/", partName="parameters") SucheLGKDokumenteV1 parameters);

  /**
   * @param asyncHandler
   * @param parameters
   *
   * @return returns java.util.concurrent.Future<? extends java.lang.Object>
   */
  @WebMethod(operationName="sucheLGKDokumenteV1")
  public Future<?> sucheLGKDokumenteV1Async(
		  @WebParam(name="sucheLGKDokumenteV1", targetNamespace="http://v20.focus360.webservice.lgkk.stp.sozvers.at/", partName="parameters") SucheLGKDokumenteV1 parameters,
		  @WebParam(name="sucheLGKDokumenteV1Response", targetNamespace="", partName="asyncHandler") AsyncHandler<SucheLGKDokumenteV1Response> asyncHandler);

  /**
   * @param parameters
   *
   * @return returns javax.xml.ws.Response<at.sozvers.stp.lgkk.webservice.focus360.v20.SucheLGKDokumenteV1Response>
   */
  @WebMethod(operationName="sucheLGKDokumenteV1")
  public Response<SucheLGKDokumenteV1Response> sucheLGKDokumenteV1Async(
		  @WebParam(name="sucheLGKDokumenteV1", targetNamespace="http://v20.focus360.webservice.lgkk.stp.sozvers.at/", partName="parameters") SucheLGKDokumenteV1 parameters);

  /**
   * @param parameters
   *
   * @return returns at.sozvers.stp.lgkk.webservice.focus360.v20.SucheLGKFaelleV2Response
   */
  @WebMethod
  @WebResult(name="sucheLGKFaelleV2Response", targetNamespace="http://v20.focus360.webservice.lgkk.stp.sozvers.at/", partName="parameters")
  public SucheLGKFaelleV2Response sucheLGKFaelleV2(
		  @WebParam(name="sucheLGKFaelleV2", targetNamespace="http://v20.focus360.webservice.lgkk.stp.sozvers.at/", partName="parameters") SucheLGKFaelleV2 parameters);

  /**
   * @param asyncHandler
   * @param parameters
   *
   * @return returns java.util.concurrent.Future<? extends java.lang.Object>
   */
  @WebMethod(operationName="sucheLGKFaelleV2")
  public Future<?> sucheLGKFaelleV2Async(@WebParam(name="sucheLGKFaelleV2", targetNamespace="http://v20.focus360.webservice.lgkk.stp.sozvers.at/", partName="parameters") SucheLGKFaelleV2 parameters,
										 @WebParam(name="sucheLGKFaelleV2Response", targetNamespace="", partName="asyncHandler") AsyncHandler<SucheLGKFaelleV2Response> asyncHandler);

  /**
   * @param parameters
   *
   * @return returns javax.xml.ws.Response<at.sozvers.stp.lgkk.webservice.focus360.v20.SucheLGKFaelleV2Response>
   */
  @WebMethod(operationName="sucheLGKFaelleV2")
  public Response<SucheLGKFaelleV2Response> sucheLGKFaelleV2Async(
		  @WebParam(name="sucheLGKFaelleV2", targetNamespace="http://v20.focus360.webservice.lgkk.stp.sozvers.at/", partName="parameters") SucheLGKFaelleV2 parameters);
}
