package at.itsv.sap.pi.egov.zup.v7;

import javax.xml.namespace.QName;
import java.net.URL;
import jakarta.xml.ws.*;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.3.2 Generated source version: 2.2
 */
@WebServiceClient(name="ZUP_Protokolle_OUTBOUND_SYNCService", targetNamespace="urn:itsv.at:sap:pi:egov:zup:v7")
public class ZUPProtokolleOUTBOUNDSYNCService extends Service {

  private final static QName  ZUPPROTOKOLLEOUTBOUNDSYNCSERVICE_QNAME = new QName("urn:itsv.at:sap:pi:egov:zup:v7", "ZUP_Protokolle_OUTBOUND_SYNCService");
  private final static URL    ZUPPROTOKOLLEOUTBOUNDSYNCSERVICE_WSDL_LOCATION;
  private final static Logger logger                                 = LoggerFactory.getLogger(at.itsv.sap.pi.egov.zup.v7.ZUPProtokolleOUTBOUNDSYNCService.class.getName());

  static {
	ZUPPROTOKOLLEOUTBOUNDSYNCSERVICE_WSDL_LOCATION = ZUPProtokolleOUTBOUNDSYNCService.class.getResource("/wsdl/ZUP_Protokolle_v7.wsdl");
	logger.info(ZUPPROTOKOLLEOUTBOUNDSYNCSERVICE_WSDL_LOCATION.toString());
  }

  public ZUPProtokolleOUTBOUNDSYNCService() {
	super(__getWsdlLocation(), ZUPPROTOKOLLEOUTBOUNDSYNCSERVICE_QNAME);
  }

  private static URL __getWsdlLocation() {
	return ZUPPROTOKOLLEOUTBOUNDSYNCSERVICE_WSDL_LOCATION;
  }

  public ZUPProtokolleOUTBOUNDSYNCService(WebServiceFeature... features) {
	super(__getWsdlLocation(), ZUPPROTOKOLLEOUTBOUNDSYNCSERVICE_QNAME, features);
  }

  public ZUPProtokolleOUTBOUNDSYNCService(URL wsdlLocation) {
	super(wsdlLocation, ZUPPROTOKOLLEOUTBOUNDSYNCSERVICE_QNAME);
  }

  public ZUPProtokolleOUTBOUNDSYNCService(URL wsdlLocation, WebServiceFeature... features) {
	super(wsdlLocation, ZUPPROTOKOLLEOUTBOUNDSYNCSERVICE_QNAME, features);
  }

  public ZUPProtokolleOUTBOUNDSYNCService(URL wsdlLocation, QName serviceName) {
	super(wsdlLocation, serviceName);
  }

  public ZUPProtokolleOUTBOUNDSYNCService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
	super(wsdlLocation, serviceName, features);
  }

  /**
   * @return returns ZUPProtokolleOUTBOUNDSYNC
   */
  @WebEndpoint(name="DEV")
  public ZUPProtokolleOUTBOUNDSYNC getDEV() {
	return super.getPort(new QName("urn:itsv.at:sap:pi:egov:zup:v7", "DEV"), ZUPProtokolleOUTBOUNDSYNC.class);
  }

  /**
   * @param features
   * 		A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
   *
   * @return returns ZUPProtokolleOUTBOUNDSYNC
   */
  @WebEndpoint(name="DEV")
  public ZUPProtokolleOUTBOUNDSYNC getDEV(WebServiceFeature... features) {
	return super.getPort(new QName("urn:itsv.at:sap:pi:egov:zup:v7", "DEV"), ZUPProtokolleOUTBOUNDSYNC.class, features);
  }

  /**
   * @return returns ZUPProtokolleOUTBOUNDSYNC
   */
  @WebEndpoint(name="PROD")
  public ZUPProtokolleOUTBOUNDSYNC getPROD() {
	return super.getPort(new QName("urn:itsv.at:sap:pi:egov:zup:v7", "PROD"), ZUPProtokolleOUTBOUNDSYNC.class);
  }

  /**
   * @param features
   * 		A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
   *
   * @return returns ZUPProtokolleOUTBOUNDSYNC
   */
  @WebEndpoint(name="PROD")
  public ZUPProtokolleOUTBOUNDSYNC getPROD(WebServiceFeature... features) {
	return super.getPort(new QName("urn:itsv.at:sap:pi:egov:zup:v7", "PROD"), ZUPProtokolleOUTBOUNDSYNC.class, features);
  }

  /**
   * @return returns ZUPProtokolleOUTBOUNDSYNC
   */
  @WebEndpoint(name="TEST")
  public ZUPProtokolleOUTBOUNDSYNC getTEST() {
	return super.getPort(new QName("urn:itsv.at:sap:pi:egov:zup:v7", "TEST"), ZUPProtokolleOUTBOUNDSYNC.class);
  }

  /**
   * @param features
   * 		A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
   *
   * @return returns ZUPProtokolleOUTBOUNDSYNC
   */
  @WebEndpoint(name="TEST")
  public ZUPProtokolleOUTBOUNDSYNC getTEST(WebServiceFeature... features) {
	return super.getPort(new QName("urn:itsv.at:sap:pi:egov:zup:v7", "TEST"), ZUPProtokolleOUTBOUNDSYNC.class, features);
  }
}
