package at.itsv.sap.pi.egov.zup.v7;

import com.oracle.xmlns.zupws.*;
import jakarta.jws.*;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.3.2 Generated source version: 2.2
 */
@WebService(name="ZUP_Protokolle_OUTBOUND_SYNC", targetNamespace="urn:itsv.at:sap:pi:egov:zup:v7")
@SOAPBinding(parameterStyle=SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({ObjectFactory.class})
public interface ZUPProtokolleOUTBOUNDSYNC {

  /**
   * @param payload
   *
   * @return returns com.oracle.xmlns.zupws.ZupwsProcessResponse
   */
  @WebMethod(operationName="ZUP_Protokolle_OUTBOUND_SYNC", action="http://sap.com/xi/WebService/soap1.1")
  @WebResult(name="ZupwsProcessResponse", targetNamespace="http://xmlns.oracle.com/Zupws", partName="payload")
  public ZupwsProcessResponse zupProtokolleOUTBOUNDSYNC(@WebParam(name="Protokolle", targetNamespace="http://xmlns.oracle.com/Zupws", partName="payload") Protokolle payload);
}
