package at.siemens.ecard.server.onlineservices;

import javax.xml.namespace.QName;
import java.net.MalformedURLException;
import java.net.URL;
import jakarta.xml.ws.*;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.7-b01- Generated source version: 2.1
 */
@WebServiceClient(name="OnlineServices_Focus360_Service", targetNamespace="http://onlineservices.server.ecard.siemens.at",
				  wsdlLocation="file:/C:/ta30/IdeaProjects/FRONTEND/focus-ws-clients/focus-ecard-ws-client/src/main/resources/wsdl/OnlineServices/OnlineServices.wsdl")
public class OnlineServicesFocus360Service extends Service {

  private static final URL    ONLINESERVICESFOCUS360SERVICE_WSDL_LOCATION;
  private static final String SIEMENSURI = "http://onlineservices.server.ecard.siemens.at";
  private static final Logger logger     = LoggerFactory.getLogger(at.siemens.ecard.server.onlineservices.OnlineServicesFocus360Service.class.getName());

  static {
	URL url = null;
	try {
	  URL baseUrl;
	  baseUrl = at.siemens.ecard.server.onlineservices.OnlineServicesFocus360Service.class.getResource(".");
	  url = new URL(baseUrl, "file:/C:/ta30/IdeaProjects/FRONTEND/focus-ws-clients/focus-ecard-ws-client/src/main/resources/wsdl/OnlineServices/OnlineServices.wsdl");
	} catch(MalformedURLException e) {
	  logger.warn(
			  "Failed to create URL for the wsdl Location: 'file:/C:/ta30/IdeaProjects/FRONTEND/focus-ws-clients/focus-ecard-ws-client/src/main/resources/wsdl/OnlineServices/OnlineServices.wsdl', retrying as a local file");
	  logger.warn(e.getMessage(), e);
	}
	ONLINESERVICESFOCUS360SERVICE_WSDL_LOCATION = url;
  }

  public OnlineServicesFocus360Service(URL wsdlLocation, QName serviceName) {
	super(wsdlLocation, serviceName);
  }

  public OnlineServicesFocus360Service() {
	super(ONLINESERVICESFOCUS360SERVICE_WSDL_LOCATION, new QName(SIEMENSURI, "OnlineServices_Focus360_Service"));
  }

  /**
   * @return returns OnlineServicesFocus360
   */
  @WebEndpoint(name="OnlineServicesFocus360")
  public OnlineServicesFocus360 getOnlineServicesFocus360() {
	return super.getPort(new QName(SIEMENSURI, "OnlineServicesFocus360"), OnlineServicesFocus360.class);
  }

  /**
   * @param features
   * 		A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
   *
   * @return returns OnlineServicesFocus360
   */
  @WebEndpoint(name="OnlineServicesFocus360")
  public OnlineServicesFocus360 getOnlineServicesFocus360(WebServiceFeature... features) {
	return super.getPort(new QName(SIEMENSURI, "OnlineServicesFocus360"), OnlineServicesFocus360.class, features);
  }
}
