package at.sozvers.noegkk.sckont.kundenfeedback.focus;

import javax.xml.namespace.QName;
import java.net.MalformedURLException;
import java.net.URL;
import jakarta.xml.ws.*;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.6b21 Generated source version: 2.2
 */
@WebServiceClient(name="SCKONTFeedbackService_1_0Service", targetNamespace="http://focus.kundenfeedback.sckont.noegkk.sozvers.at/",
				  wsdlLocation="file:/C:/ta30/IntellijProjects/FRONTEND/focus-ws-clients/focus-feedback-ws-client/src/main/resources/wsdl/SCKONTFeedbackService_1_0.wsdl")
public class SCKONTFeedbackService10Service extends Service {

  private final static WebServiceException SCKONTFEEDBACKSERVICE10SERVICE_EXCEPTION;
  private final static QName               SCKONTFEEDBACKSERVICE10SERVICE_QNAME = new QName("http://focus.kundenfeedback.sckont.noegkk.sozvers.at/", "SCKONTFeedbackService_1_0Service");
  private final static URL                 SCKONTFEEDBACKSERVICE10SERVICE_WSDL_LOCATION;

  static {
	URL                 url = null;
	WebServiceException e   = null;
	try {
	  url = new URL("file:/C:/ta30/IntellijProjects/FRONTEND/focus-ws-clients/focus-feedback-ws-client/src/main/resources/wsdl/SCKONTFeedbackService_1_0.wsdl");
	} catch(MalformedURLException ex) {
	  e = new WebServiceException(ex);
	}
	SCKONTFEEDBACKSERVICE10SERVICE_WSDL_LOCATION = url;
	SCKONTFEEDBACKSERVICE10SERVICE_EXCEPTION = e;
  }

  public SCKONTFeedbackService10Service() {
	super(__getWsdlLocation(), SCKONTFEEDBACKSERVICE10SERVICE_QNAME);
  }

  private static URL __getWsdlLocation() {
	if(SCKONTFEEDBACKSERVICE10SERVICE_EXCEPTION != null) {
	  throw SCKONTFEEDBACKSERVICE10SERVICE_EXCEPTION;
	}
	return SCKONTFEEDBACKSERVICE10SERVICE_WSDL_LOCATION;
  }

  public SCKONTFeedbackService10Service(WebServiceFeature... features) {
	super(__getWsdlLocation(), SCKONTFEEDBACKSERVICE10SERVICE_QNAME, features);
  }

  public SCKONTFeedbackService10Service(URL wsdlLocation) {
	super(wsdlLocation, SCKONTFEEDBACKSERVICE10SERVICE_QNAME);
  }

  public SCKONTFeedbackService10Service(URL wsdlLocation, WebServiceFeature... features) {
	super(wsdlLocation, SCKONTFEEDBACKSERVICE10SERVICE_QNAME, features);
  }

  public SCKONTFeedbackService10Service(URL wsdlLocation, QName serviceName) {
	super(wsdlLocation, serviceName);
  }

  public SCKONTFeedbackService10Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
	super(wsdlLocation, serviceName, features);
  }

  /**
   * @return returns SCKONTFeedbackService10
   */
  @WebEndpoint(name="SCKONTFeedbackService_1_0Port")
  public SCKONTFeedbackService10 getSCKONTFeedbackService10Port() {
	return super.getPort(new QName("http://focus.kundenfeedback.sckont.noegkk.sozvers.at/", "SCKONTFeedbackService_1_0Port"), SCKONTFeedbackService10.class);
  }

  /**
   * @param features
   * 		A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
   *
   * @return returns SCKONTFeedbackService10
   */
  @WebEndpoint(name="SCKONTFeedbackService_1_0Port")
  public SCKONTFeedbackService10 getSCKONTFeedbackService10Port(WebServiceFeature... features) {
	return super.getPort(new QName("http://focus.kundenfeedback.sckont.noegkk.sozvers.at/", "SCKONTFeedbackService_1_0Port"), SCKONTFeedbackService10.class, features);
  }
}
