package at.sozvers.kva.definitions.ermittle_krankenversicherungsanspruch;

import at.sozvers.kva.schema.ermittle_krankenversicherungsanspruch.ErmittelterKrankenversicherungsanspruch;
import at.sozvers.kva.schema.ermittle_krankenversicherungsanspruch.KrankenversicherungsanspruchErmittlung;
import jakarta.jws.*;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.3.2 Generated source version: 2.2
 */
@WebService(name="ErmittleKrankenversicherungsanspruch", targetNamespace="http://kva.sozvers.at/definitions/ermittle-krankenversicherungsanspruch")
@SOAPBinding(parameterStyle=SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({at.sozvers.kva.schema.ermittle_krankenversicherungsanspruch.ObjectFactory.class, at.sozvers.kva.schema.types.ObjectFactory.class})
public interface ErmittleKrankenversicherungsanspruch {

  /**
   * @param krankenversicherungsanspruchErmittlung
   *
   * @return returns at.sozvers.kva.schema.ermittle_krankenversicherungsanspruch.ErmittelterKrankenversicherungsanspruch
   */
  @WebMethod(action="ermittleKrankenversicherungsanspruch")
  @WebResult(name="ermittelterKrankenversicherungsanspruch", targetNamespace="http://kva.sozvers.at/schema/ermittle-krankenversicherungsanspruch", partName="ermittelterKrankenversicherungsanspruch")
  public ErmittelterKrankenversicherungsanspruch ermittleKrankenversicherungsanspruch(
		  @WebParam(name="krankenversicherungsanspruchErmittlung", targetNamespace="http://kva.sozvers.at/schema/ermittle-krankenversicherungsanspruch",
					partName="krankenversicherungsanspruchErmittlung") KrankenversicherungsanspruchErmittlung krankenversicherungsanspruchErmittlung);
}
