-- psql -f .\init_db_local.sql -U postgres

DROP DATABASE IF EXISTS focus_dev_local;
REVOKE ALL ON ALL TABLES IN SCHEMA public FROM focus CASCADE;
DROP TABLESPACE IF EXISTS focus;
DROP USER IF EXISTS focus;

CREATE USER focus WITH
    LOGIN
    NOSUPERUSER
    INHERIT
    NOCREATEDB
    NOCREATEROLE
    NOBYPASSRLS
    NOREPLICATION
    CONNECTION LIMIT -1
    ENCRYPTED PASSWORD 'focus';
CREATE TABLESPACE focus
    OWNER focus
    LOCATION 'C:\TA30\Server\Postgres_DB';
CREATE DATABASE focus_dev_local WITH
    OWNER = focus
    ENCODING = 'UTF8'
    LC_COLLATE = 'German_Austria.1252'
    LC_CTYPE = 'German_Austria.1252'
    CONNECTION LIMIT = -1
    TABLESPACE = focus;