package at.sozvers.noegkk.sckont.beschwerde.focus;

import javax.xml.namespace.QName;
import java.net.MalformedURLException;
import java.net.URL;
import jakarta.xml.ws.*;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.7-b01- Generated source version: 2.1
 */
@WebServiceClient(name="SCKONTBeschwerdeService_1_0Service", targetNamespace="http://focus.beschwerde.sckont.noegkk.sozvers.at/",
				  wsdlLocation="file:/C:/ta30/git-repos/FOCUS/focus-ws-clients/focus-scapp-ws-client/src/main/resources/wsdl/Scappws.wsdl")
public class SCKONTBeschwerdeService10Service extends Service {

  private static final String BASICURI = "http://focus.beschwerde.sckont.noegkk.sozvers.at/";
  private static final URL    SCKONTBESCHWERDESERVICE10SERVICE_WSDL_LOCATION;
  private static final Logger logger   = LoggerFactory.getLogger(at.sozvers.noegkk.sckont.beschwerde.focus.SCKONTBeschwerdeService10Service.class.getName());

  static {
	URL url = null;
	try {
	  URL baseUrl;
	  baseUrl = at.sozvers.noegkk.sckont.beschwerde.focus.SCKONTBeschwerdeService10Service.class.getResource(".");
	  url = new URL(baseUrl, "file:/C:/ta30/git-repos/FOCUS/focus-ws-clients/focus-scapp-ws-client/src/main/resources/wsdl/Scappws.wsdl");
	} catch(MalformedURLException e) {
	  logger.warn("Failed to create URL for the wsdl Location: 'file:/C:/ta30/git-repos/FOCUS/focus-ws-clients/focus-scapp-ws-client/src/main/resources/wsdl/Scappws.wsdl', retrying as a local file");
	  logger.warn(e.getMessage(), e);
	}
	SCKONTBESCHWERDESERVICE10SERVICE_WSDL_LOCATION = url;
  }

  public SCKONTBeschwerdeService10Service(URL wsdlLocation, QName serviceName) {
	super(wsdlLocation, serviceName);
  }

  public SCKONTBeschwerdeService10Service() {
	super(SCKONTBESCHWERDESERVICE10SERVICE_WSDL_LOCATION, new QName(BASICURI, "SCKONTBeschwerdeService_1_0Service"));
  }

  /**
   * @return returns SCKONTBeschwerdeService10
   */
  @WebEndpoint(name="SCKONTBeschwerdeService_1_0Port")
  public SCKONTBeschwerdeService10 getSCKONTBeschwerdeService10Port() {
	return super.getPort(new QName(BASICURI, "SCKONTBeschwerdeService_1_0Port"), SCKONTBeschwerdeService10.class);
  }

  /**
   * @param features
   * 		A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
   *
   * @return returns SCKONTBeschwerdeService10
   */
  @WebEndpoint(name="SCKONTBeschwerdeService_1_0Port")
  public SCKONTBeschwerdeService10 getSCKONTBeschwerdeService10Port(WebServiceFeature... features) {
	return super.getPort(new QName(BASICURI, "SCKONTBeschwerdeService_1_0Port"), SCKONTBeschwerdeService10.class, features);
  }
}
