package at.sozvers.noegkk.sckont.beschwerde.focus;

import jakarta.jws.*;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.7-b01- Generated source version: 2.1
 */
@WebService(name="SCKONTBeschwerdeService_1_0", targetNamespace="http://focus.beschwerde.sckont.noegkk.sozvers.at/")
@SOAPBinding(parameterStyle=SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({ObjectFactory.class})
public interface SCKONTBeschwerdeService10 {

  /**
   * @param beschwerdeAendern
   *
   * @return returns at.sozvers.noegkk.sckont.beschwerde.focus.BeschwerdeAendernResponse
   */
  @WebMethod
  @WebResult(name="beschwerdeAendernResponse", targetNamespace="http://focus.beschwerde.sckont.noegkk.sozvers.at/", partName="beschwerdeAendernResponse")
  public BeschwerdeAendernResponse beschwerdeAendern(
		  @WebParam(name="beschwerdeAendern", targetNamespace="http://focus.beschwerde.sckont.noegkk.sozvers.at/", partName="beschwerdeAendern") BeschwerdeAendernRequest beschwerdeAendern);

  /**
   * @param beschwerdeErstellen
   *
   * @return returns at.sozvers.noegkk.sckont.beschwerde.focus.BeschwerdeErstellenResponse
   */
  @WebMethod
  @WebResult(name="beschwerdeErstellenResponse", targetNamespace="http://focus.beschwerde.sckont.noegkk.sozvers.at/", partName="beschwerdeErstellenResponse")
  public BeschwerdeErstellenResponse beschwerdeErstellen(
		  @WebParam(name="beschwerdeErstellen", targetNamespace="http://focus.beschwerde.sckont.noegkk.sozvers.at/", partName="beschwerdeErstellen") BeschwerdeErstellenRequest beschwerdeErstellen);

  /**
   * @param beschwerdeLesen
   *
   * @return returns at.sozvers.noegkk.sckont.beschwerde.focus.BeschwerdeLesenResponse
   */
  @WebMethod
  @WebResult(name="beschwerdeLesenResponse", targetNamespace="http://focus.beschwerde.sckont.noegkk.sozvers.at/", partName="beschwerdeLesenResponse")
  public BeschwerdeLesenResponse beschwerdeLesen(
		  @WebParam(name="beschwerdeLesen", targetNamespace="http://focus.beschwerde.sckont.noegkk.sozvers.at/", partName="beschwerdeLesen") BeschwerdeLesenRequest beschwerdeLesen);

  /**
   * @param beschwerdeStornieren
   *
   * @return returns at.sozvers.noegkk.sckont.beschwerde.focus.BeschwerdeStornierenResponse
   */
  @WebMethod
  @WebResult(name="beschwerdeStornierenResponse", targetNamespace="http://focus.beschwerde.sckont.noegkk.sozvers.at/", partName="beschwerdeStornierenResponse")
  public BeschwerdeStornierenResponse beschwerdeStornieren(@WebParam(name="beschwerdeStornieren", targetNamespace="http://focus.beschwerde.sckont.noegkk.sozvers.at/",
																	 partName="beschwerdeStornieren") BeschwerdeStornierenRequest beschwerdeStornieren);

  /**
   * @param beschwerdebereichErmitteln
   *
   * @return returns at.sozvers.noegkk.sckont.beschwerde.focus.BeschwerdebereichErmittelnResponse
   */
  @WebMethod
  @WebResult(name="beschwerdebereichErmittelnResponse", targetNamespace="http://focus.beschwerde.sckont.noegkk.sozvers.at/", partName="beschwerdebereichErmittelnResponse")
  public BeschwerdebereichErmittelnResponse beschwerdebereichErmitteln(@WebParam(name="beschwerdebereichErmitteln", targetNamespace="http://focus.beschwerde.sckont.noegkk.sozvers.at/",
																				 partName="beschwerdebereichErmitteln") BeschwerdebereichErmittelnRequest beschwerdebereichErmitteln);

  /**
   * @param beschwerdenErmitteln
   *
   * @return returns at.sozvers.noegkk.sckont.beschwerde.focus.BeschwerdenErmittelnResponse
   */
  @WebMethod
  @WebResult(name="beschwerdenErmittelnResponse", targetNamespace="http://focus.beschwerde.sckont.noegkk.sozvers.at/", partName="beschwerdenErmittelnResponse")
  public BeschwerdenErmittelnResponse beschwerdenErmitteln(@WebParam(name="beschwerdenErmitteln", targetNamespace="http://focus.beschwerde.sckont.noegkk.sozvers.at/",
																	 partName="beschwerdenErmitteln") BeschwerdenErmittelnRequest beschwerdenErmitteln);
}
