package at.sozvers.zvd.ws.versicherungsverhaeltnisselesenservice.v3;

import at.sozvers.zvd.ws.versicherungsverhaeltnisselesenservice.v3.types.VersicherungsverhaeltnisseLesenRequest;
import at.sozvers.zvd.ws.versicherungsverhaeltnisselesenservice.v3.types.VersicherungsverhaeltnisseLesenResponse;
import jakarta.jws.*;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.6b21 Generated source version: 2.2
 */
@WebService(name="VersicherungsverhaeltnisseLesenService", targetNamespace="http://sozvers.at/zvd/ws/VersicherungsverhaeltnisseLesenService/v3")
@XmlSeeAlso({at.itsv.services.svstd11.types.ObjectFactory.class, at.sozvers.zvd.ws.versicherungsverhaeltnisselesenservice.v3.ObjectFactory.class,
		at.sozvers.zvd.ws.versicherungsverhaeltnisselesenservice.v3.types.ObjectFactory.class})
public interface VersicherungsverhaeltnisseLesenService {

  /**
   * @param request
   *
   * @return returns at.sozvers.zvd.ws.versicherungsverhaeltnisselesenservice.v3.types.VersicherungsverhaeltnisseLesenResponse
   */
  @WebMethod(operationName="VersicherungsverhaeltnisseLesen", action="http://sozvers.at/zvd/ws/VersicherungsverhaeltnisseLesenService/v3/VersicherungsverhaeltnisseLesen")
  @WebResult(name="Response", targetNamespace="http://sozvers.at/zvd/ws/VersicherungsverhaeltnisseLesenService/v3/types")
  @RequestWrapper(localName="VersicherungsverhaeltnisseLesen", targetNamespace="http://sozvers.at/zvd/ws/VersicherungsverhaeltnisseLesenService/v3",
				  className="at.sozvers.zvd.ws.versicherungsverhaeltnisselesenservice.v3.types.VersicherungsverhaeltnisseLesenRequestWrapper")
  @ResponseWrapper(localName="VersicherungsverhaeltnisseLesenResponse", targetNamespace="http://sozvers.at/zvd/ws/VersicherungsverhaeltnisseLesenService/v3",
				   className="at.sozvers.zvd.ws.versicherungsverhaeltnisselesenservice.v3.types.VersicherungsverhaeltnisseLesenResponseWrapper")
  public VersicherungsverhaeltnisseLesenResponse versicherungsverhaeltnisseLesen(
		  @WebParam(name="Request", targetNamespace="http://sozvers.at/zvd/ws/VersicherungsverhaeltnisseLesenService/v3/types") VersicherungsverhaeltnisseLesenRequest request);
}
