package at.sozvers.zvd.ws.versicherungsverhaeltnisselesenservice.v3;

import javax.xml.namespace.QName;
import java.net.MalformedURLException;
import java.net.URL;
import jakarta.xml.ws.*;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.6b21 Generated source version: 2.2
 */
@WebServiceClient(name="VersicherungsverhaeltnisseLesen", targetNamespace="http://sozvers.at/zvd/ws/VersicherungsverhaeltnisseLesenService/v3",
				  wsdlLocation="file:/C:/ta3j/workspaces/QDASH/focus-ws-clients/focus-zvd-ws-client/src/main/resources/wsdl/VersicherungsverhaeltnisseLesen_3_0/VersicherungsverhaeltnisseLesen_3_0.wsdl")
public class VersicherungsverhaeltnisseLesen extends Service {

  private final static WebServiceException VERSICHERUNGSVERHAELTNISSELESEN_EXCEPTION;
  private final static QName               VERSICHERUNGSVERHAELTNISSELESEN_QNAME = new QName("http://sozvers.at/zvd/ws/VersicherungsverhaeltnisseLesenService/v3", "VersicherungsverhaeltnisseLesen");
  private final static URL                 VERSICHERUNGSVERHAELTNISSELESEN_WSDL_LOCATION;

  static {
	URL                 url = null;
	WebServiceException e   = null;
	try {
	  url = new URL("file:/C:/ta3j/workspaces/QDASH/focus-ws-clients/focus-zvd-ws-client/src/main/resources/wsdl/VersicherungsverhaeltnisseLesen_3_0/VersicherungsverhaeltnisseLesen_3_0.wsdl");
	} catch(MalformedURLException ex) {
	  e = new WebServiceException(ex);
	}
	VERSICHERUNGSVERHAELTNISSELESEN_WSDL_LOCATION = url;
	VERSICHERUNGSVERHAELTNISSELESEN_EXCEPTION = e;
  }

  public VersicherungsverhaeltnisseLesen() {
	super(__getWsdlLocation(), VERSICHERUNGSVERHAELTNISSELESEN_QNAME);
  }

  private static URL __getWsdlLocation() {
	if(VERSICHERUNGSVERHAELTNISSELESEN_EXCEPTION != null) {
	  throw VERSICHERUNGSVERHAELTNISSELESEN_EXCEPTION;
	}
	return VERSICHERUNGSVERHAELTNISSELESEN_WSDL_LOCATION;
  }

  public VersicherungsverhaeltnisseLesen(WebServiceFeature... features) {
	super(__getWsdlLocation(), VERSICHERUNGSVERHAELTNISSELESEN_QNAME, features);
  }

  public VersicherungsverhaeltnisseLesen(URL wsdlLocation) {
	super(wsdlLocation, VERSICHERUNGSVERHAELTNISSELESEN_QNAME);
  }

  public VersicherungsverhaeltnisseLesen(URL wsdlLocation, WebServiceFeature... features) {
	super(wsdlLocation, VERSICHERUNGSVERHAELTNISSELESEN_QNAME, features);
  }

  public VersicherungsverhaeltnisseLesen(URL wsdlLocation, QName serviceName) {
	super(wsdlLocation, serviceName);
  }

  public VersicherungsverhaeltnisseLesen(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
	super(wsdlLocation, serviceName, features);
  }

  /**
   * @return returns VersicherungsverhaeltnisseLesenService
   */
  @WebEndpoint(name="VersicherungsverhaeltnisseLesenPort")
  public VersicherungsverhaeltnisseLesenService getVersicherungsverhaeltnisseLesenPort() {
	return super.getPort(new QName("http://sozvers.at/zvd/ws/VersicherungsverhaeltnisseLesenService/v3", "VersicherungsverhaeltnisseLesenPort"), VersicherungsverhaeltnisseLesenService.class);
  }

  /**
   * @param features
   * 		A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
   *
   * @return returns VersicherungsverhaeltnisseLesenService
   */
  @WebEndpoint(name="VersicherungsverhaeltnisseLesenPort")
  public VersicherungsverhaeltnisseLesenService getVersicherungsverhaeltnisseLesenPort(WebServiceFeature... features) {
	return super.getPort(new QName("http://sozvers.at/zvd/ws/VersicherungsverhaeltnisseLesenService/v3", "VersicherungsverhaeltnisseLesenPort"), VersicherungsverhaeltnisseLesenService.class,
						 features);
  }
}
